language: rust

rust:
  - stable
  - nightly

jobs:
  include:
    - stage: build
      script: cargo build
    
    - stage: test
      script: cargo test

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
