language: rust

rust:
  - stable
  - nightly

matrix:
  include:
    - name: build
      script: cargo build
    
    - name: test
      script: cargo test

  allow_failures:
    - rust: nightly
  fast_finish: true